# This is a basic workflow to help you get started with Actions

name: Docker CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: docker login
        env: 
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: | 
          docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
      
      # Runs a single command using the runners shell
      - name: Docker build app1
        run: |
          docker build ./app-1 -t ridavera/github-repo:2.0
          
      - name: Docker build app2
        run: |
          docker build ./app-2 -t ridavera/github-repo:2.0
          
      - name: Docker build nginx
        run: |
          docker build ./nginx -t ridavera/github-repo:2.0
          
      
          
      #- name: Dockerhub push 
        #run: |
         # docker push ridavera/app-1 
          #docker push ridavera/app-2 
         # docker push ridavera/nginx
        
          
